### ISSUE TITLE
Participate/cowork with Arch Summit Shenzhen

### ISSUE THREAD

**Issue by paulvi** [szjug/szjug.github.io#12]
http://sz2016.archsummit.com/ 2016年7月15日~16日

**Comment by paulvi** [comment]
Also OPS summit http://gops2016-shenzhen.eventdove.com/ 3月25日-26日

list http://www.eventdove.com/events?a=%E6%B7%B1%E5%9C%B3&c=1&t=0&s=1&k=%E6%8A%80%E6%9C%AF

**Comment by rysiekblah** [comment]
but these 2 events only for locals, we have to change it in China and create more international events, in Poland we have conferences and ~70% lectures in English

**Comment by paulvi** [comment]
Yes, that is where China is different from Europe.

Actually before on QCon there were often talks in English, but now I see most events have 100% Chinese presenters. It is too big challenge for 50% and 10% would understand enough to learn something new.

Would you present in ArchSummit? I will help to push your talk. For myself I have not decided on topic there.

**Comment by paulvi** [comment]
This event is organized by InfoqQ china http://www.infoq.com

**Comment by rysiekblah** [comment]
in terms of ArchSummit, it is on July, I'm not really sure if I'm still in China :(

**Comment by paulvi** [comment]
well, I am 99% sure I will be in Shenzhen, so planning for this year

**Comment by paulvi** [comment]
It just went out of my view. Conference passed 100% in Chinese
