### ISSUE TITLE
Scala / Clojure / Kotlin / ... JVM languages SIG? ~May 28, Sat

### ISSUE THREAD

**Issue by tomtau** [szjug/szjug.github.io#16]
With HKFP, we are planning an event in SZ:
http://www.meetup.com/HK-Functional-programming/events/229363519/

One speaker is confirmed. It's Tiger Chan who blogs about Scalaz: http://www.cnblogs.com/tiger-xc/

We are looking for a venue and other people interested, so it could be good to join forces with SZJUG and start a Scala SIG?

**Comment by paulvi** [comment]
Our Scala guru is @rysiekblah Tomasz

@tomtau
As meetup.com is blocked in China, are you OK with parallel registration on http://szjug.github.io/

And we name for it. How about "Scala / Clojure / Kotlin / ... JVM languages SIG - joint event with HKFP" ?

But personally I am tired a bit of week-end events, besides will there be more than 2-3 speakers?

**Comment by paulvi** [comment]
There is also Spring Boot to go in May #15, already 2 speakers (me and @picaro)

**Comment by tomtau** [comment]
@paulvi 
Oh, I didn't know meetup.com was blocked (I remember accessing it in China) - anyway, in that case, the parallel registration is fine; I'll take http://szjug.github.io/ as the main place for registration and redirect people from the Meetup event to confirm their registration there (to have an exact number of attendees in one place).

I guess the name is fine for now.

A few people may be coming over from HK (including myself), so I'm afraid a weekend event is unavoidable in this case. I also plan to give a talk, but only a short lightning one.

When exactly is Spring Boot?

**Comment by paulvi** [comment]
@tomtau Speakers make the event. If there is less than 2 speakers, I propose to merge this event with Spring Boot event #15 
(or do later)

Spring Boot is one of project withing Spring http://projects.spring.io/spring-boot/
(There was SpringSource company bought, that was by VMware, that was bought by EMC, and now bought by Dell  )
Spring is No 1 framework for Java, especially in China, but Spring Boot is relatively.
Come to learn, it will be hands-on experience

The smallest app, then responds to http://localhost:8080/ saying hello

``` java
package hello;

import org.springframework.boot.*;
import org.springframework.boot.autoconfigure.*;
import org.springframework.stereotype.*;
import org.springframework.web.bind.annotation.*;

@Controller
@EnableAutoConfiguration
public class SampleController {

    @RequestMapping("/")
    @ResponseBody
    String home() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        SpringApplication.run(SampleController.class, args);
    }
}
```

**Comment by tomtau** [comment]
@paulvi If Spring Boot event #15 was meant to be towards the second half / end of May (the original plan for the HKFP event was May 28), then I think it's a good idea to merge.

**Comment by paulvi** [comment]
Yes, there was no exact day announce for Spring Boot workshop,  
but we have general saying that we meet every 3rd Thursday (but it were Saturday last 2 times)

**Comment by paulvi** [comment]
I'll ask inside WeChat group and on the meeting this Saturday

**Comment by paulvi** [comment]
Are there known speakers?

**Comment by tomtau** [comment]
@chank - Akka Programming
Tiger Chan - Scalaz
me - Intro to Lambda Calculus (lightning talk)

**Comment by chank** [comment]
@tomtau I think you shouldn't have @ the wrong person.

**Comment by tomtau** [comment]
@chank apologies then
Charlie Chen @Carolusian - are there any other speakers?

**Comment by paulvi** [comment]
@tomtau check WeChat event group

**Comment by paulvi** [comment]
Event URL http://szjug.github.io/#functional-programming
- [x] 
  @tomtau What is registration for mainlanders? (non meetup option)

**Comment by tomtau** [comment]
#18

**Comment by tomtau** [comment]
#19

**Comment by paulvi** [comment]
Closing as past
