### ISSUE TITLE
#11 August 11 - Anounce

### ISSUE THREAD

**Issue by picaro** [szjug/szjug.github.io#22]
1 Introduction into Docker Ecosystem.
2 Asynchronous chat engine, based on Java NIO
3 Fast app bootstrapping with JHipster

**Comment by paulvi** [comment]
Great. Who are presenters?
Message me via WeChat with options for venue.
Then we are ready for initial invitation.

OK
1,3 by Aleksandr Pastukhov
2 by Yuri Bura

http://www.meetup.com/Shenzhen-Java-User-Group/events/233159808/

**Comment by paulvi** [comment]
https://yoopay.cn/event/94488645

**Comment by picaro** [comment]
Change, please 2 - NIO cancelled,  2 Realtime Web and Socket.IO (Juriy Bura)

**Comment by paulvi** [comment]
1 Introduction into Docker Ecosystem by Aleksandr Pastukhov
2 Realtime Web and Socket.IO by Juriy Bura
3 Fast app bootstrapping with JHipster by Aleksandr Pastukhov

**Comment by picaro** [comment]
Updated Agenda - 3 Neural Networks with Java (Peter Gordiievych)
