### ISSUE TITLE
基于spring的项目要导出成jar怎么做呢

### ISSUE THREAD

**Issue by niubiliter** [szjug/szjug.github.io#43]
Spring-based project to export into a jar to do then, the second option of eclipse is used to derive the executable jar, couldn't find the namespace, normal, in the eclipse runtime is derived when won't run, https://gitee.com/huangliusong/demo2 this is the source code, hope you glad

**Comment by paulvi** [comment]
Ask in WeChat group

**Comment by niubiliter** [comment]
问个几把
